### PR TITLE
- Removed generated files from MANIFEST as reported by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @rocky

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Review by rocky — CHANGES_REQUESTED** [review]
Thanks. Yes, I think these files should be removed from `MANIFEST`. However they then should be added to `MANIFEST.SKIP`, right? At least `Makefile`.

I am pretty sure that in my preparation for testing that `Makefile` gets created.

I see that removing Makefile removes the warning that I get in Travis CI. This is great!

 But I still have: 

```
WARNING: the following files are missing in your kit:
	lib/perlcdio.pm
	lib/perliso9660.pm
	lib/perlmmc.pm
	Makefile.PL
	META.json
	perlcdio_wrap.c
	perliso9660_wrap.c
	perlmmc_wrap.c
```

Thoughts about how to silence those?  They should appear in the tarball, but like Makefile they are all derived.

**Comment by rocky** [comment]
Not related to the pull request, but the other thing, I'd like to figure out since you mention CPANTS, is how to require the testers to make sure to have libcdio (a C program) installed. Thanks again.

**Comment by manwar** [comment]
Generally speaking, in such cases, I generate MANIFEST file as well rather than creating by hand. In your case, I would suggest, list everything you *don't* want to appear in tar ball in the MANIFEST.SKIP. Then generate your MANIFEST file like below:

make manifest 
or
Build manifest

I don't have the necessary library to test it on my dev box, otherwise I would have given you sure answer.

**Comment by rocky** [comment]
Ok. So I guess there are a couple ways to go. Either we an accept this and then I have to add to MANIFEST.SKIP or you can update the pull request. Or drop the pull request and then I'll add everything in one commit. 

Personally, I dislike deliberately making a commit that I know in advance will cause another commit to be likely, except when the change is a major refactor where it is desirable to split the changes up. 

Your thoughts?

**Comment by manwar** [comment]
I would love to help you on this but unfortunately I can't build the distribution on my dev box. Therefore I won't be able test any of the suggested changes. Hence I request you close the PR with unmerged commit.

**Comment by rocky** [comment]
Ok. I appreciate your help and thanks for the advice and your looking at this.

**Pull request closed without merging**
